services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'create database message_database_test' -U postgres
  - psql -c 'CREATE TABLE messages(id SERIAL PRIMARY KEY, url VARCHAR(100), time VARCHAR);' -U postgres
  - psql -c 'CREATE TABLE accounts(id SERIAL PRIMARY KEY, username VARCHAR, email VARCHAR, password VARCHAR)' -U postgres

script:
  - bundle exec rspec
